name: country_ip
description: > 
  Package to find users' country from their IP. 
  Dart package based on country API.
version: 2.1.0
homepage: https://github.com/NirmalAriyathilake/country_ip

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
