name: country_ip
description: > 
  Package to find users' country from their IP. 
  Dart package based on country API.
version: 3.0.0
homepage: https://github.com/NirmalAriyathilake/country_ip

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
